### ISSUE TITLE
Invalidate mongoDB credentials

### ISSUE THREAD

**Issue by Meesterbouwer123** [ratamranjith/MongoDB-Simplified#13]
Hello there, i came across this project while searching for projects that incorrectly handled the deletion of sensitive data. Unfortunately this project also made a mistake.
More specifically, when the `.env` file was deleted in commit aa5ad44, in the git log the original contents of that file are still visible.

Since the `.env` file contained the database credentials, it's easy to log in to the mongoDB instance and access everything stored there. in this case that also includes data related to several other of your projects. (see image)
![image](https://github.com/user-attachments/assets/1bcad406-60b1-4aaa-bafa-11420c28f474)

My recommendation is to change the database password, and also verify that other projects don't leak the database password in a similar manner.

**Comment by ratamranjith** [comment]
Thanks...i missed that file in .gitignore. 
Passwords has been changed.
